./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ /Users/thborges/.platformio/packages/toolchain-robcmp/lib/avr328p.rob > lls/avr328p.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/main.rob > lls/main.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/avr/avr5mcu.rob > lls/avr5mcu.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/avr/avr5regs.rob > lls/avr5regs.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/display/ssd1306.rob > lls/ssd1306.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/lib/buffer8.rob > lls/buffer8.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/lib/canvas8.rob > lls/canvas8.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/lib/databus.rob > lls/databus.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/lib/display.rob > lls/display.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/lib/mcu.rob > lls/mcu.rob.ll
./robcmp -a avr328p  -O0 -I /Users/thborges/projects/robcmp/platformio/examples/avr328p-ssd1306/src/ src/lib/ports.rob > lls/ports.rob.ll
