#line 2 "/home/alisson/Downloads/robcmp-svds_and_rp2040/build-pointer-test/Language_l.cpp"

#line 4 "/home/alisson/Downloads/robcmp-svds_and_rp2040/build-pointer-test/Language_l.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define MAIN_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer MAIN_create_buffer
#endif

#ifdef yy_delete_buffer
#define MAIN_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer MAIN_delete_buffer
#endif

#ifdef yy_scan_buffer
#define MAIN_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer MAIN_scan_buffer
#endif

#ifdef yy_scan_string
#define MAIN_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string MAIN_scan_string
#endif

#ifdef yy_scan_bytes
#define MAIN_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes MAIN_scan_bytes
#endif

#ifdef yy_init_buffer
#define MAIN_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer MAIN_init_buffer
#endif

#ifdef yy_flush_buffer
#define MAIN_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer MAIN_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define MAIN_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state MAIN_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define MAIN_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer MAIN_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define MAINpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state MAINpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define MAINpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state MAINpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define MAINensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack MAINensure_buffer_stack
#endif

#ifdef yylex
#define MAINlex_ALREADY_DEFINED
#else
#define yylex MAINlex
#endif

#ifdef yyrestart
#define MAINrestart_ALREADY_DEFINED
#else
#define yyrestart MAINrestart
#endif

#ifdef yylex_init
#define MAINlex_init_ALREADY_DEFINED
#else
#define yylex_init MAINlex_init
#endif

#ifdef yylex_init_extra
#define MAINlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra MAINlex_init_extra
#endif

#ifdef yylex_destroy
#define MAINlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy MAINlex_destroy
#endif

#ifdef yyget_debug
#define MAINget_debug_ALREADY_DEFINED
#else
#define yyget_debug MAINget_debug
#endif

#ifdef yyset_debug
#define MAINset_debug_ALREADY_DEFINED
#else
#define yyset_debug MAINset_debug
#endif

#ifdef yyget_extra
#define MAINget_extra_ALREADY_DEFINED
#else
#define yyget_extra MAINget_extra
#endif

#ifdef yyset_extra
#define MAINset_extra_ALREADY_DEFINED
#else
#define yyset_extra MAINset_extra
#endif

#ifdef yyget_in
#define MAINget_in_ALREADY_DEFINED
#else
#define yyget_in MAINget_in
#endif

#ifdef yyset_in
#define MAINset_in_ALREADY_DEFINED
#else
#define yyset_in MAINset_in
#endif

#ifdef yyget_out
#define MAINget_out_ALREADY_DEFINED
#else
#define yyget_out MAINget_out
#endif

#ifdef yyset_out
#define MAINset_out_ALREADY_DEFINED
#else
#define yyset_out MAINset_out
#endif

#ifdef yyget_leng
#define MAINget_leng_ALREADY_DEFINED
#else
#define yyget_leng MAINget_leng
#endif

#ifdef yyget_text
#define MAINget_text_ALREADY_DEFINED
#else
#define yyget_text MAINget_text
#endif

#ifdef yyget_lineno
#define MAINget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno MAINget_lineno
#endif

#ifdef yyset_lineno
#define MAINset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno MAINset_lineno
#endif

#ifdef yyget_column
#define MAINget_column_ALREADY_DEFINED
#else
#define yyget_column MAINget_column
#endif

#ifdef yyset_column
#define MAINset_column_ALREADY_DEFINED
#else
#define yyset_column MAINset_column
#endif

#ifdef yywrap
#define MAINwrap_ALREADY_DEFINED
#else
#define yywrap MAINwrap
#endif

#ifdef yyget_lval
#define MAINget_lval_ALREADY_DEFINED
#else
#define yyget_lval MAINget_lval
#endif

#ifdef yyset_lval
#define MAINset_lval_ALREADY_DEFINED
#else
#define yyset_lval MAINset_lval
#endif

#ifdef yyget_lloc
#define MAINget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc MAINget_lloc
#endif

#ifdef yyset_lloc
#define MAINset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc MAINset_lloc
#endif

#ifdef yyalloc
#define MAINalloc_ALREADY_DEFINED
#else
#define yyalloc MAINalloc
#endif

#ifdef yyrealloc
#define MAINrealloc_ALREADY_DEFINED
#else
#define yyrealloc MAINrealloc
#endif

#ifdef yyfree
#define MAINfree_ALREADY_DEFINED
#else
#define yyfree MAINfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define MAINwrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyg->yytext_ptr -= yyg->yy_more_len; \
	yyleng = (int) (yy_cp - yyg->yytext_ptr); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[233] =
    {   0,
        0,    0,    0,    0,   83,   81,    1,    1,   65,   81,
       59,   62,   81,   50,   51,   55,   57,   68,   58,   67,
       56,   78,   78,   66,   69,   46,   60,   47,   70,   48,
       49,   63,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   52,
       61,   53,   64,    3,   82,   43,    0,   79,    0,    0,
        0,   54,    2,    0,    0,   78,    0,   77,    0,    0,
       40,   44,   42,   45,   41,   70,   70,   70,   13,   70,
       70,   70,   70,   70,   70,   70,   32,   70,   70,   70,
       70,   70,   39,   70,   70,   70,   70,   28,   70,   70,

       70,   70,   70,   70,    4,    5,   80,   80,    0,    6,
       71,    0,   78,   76,   74,   38,   14,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       18,   70,   70,   70,   72,    0,    0,   75,   27,   70,
       70,   33,   31,   37,   70,   70,   70,   70,   35,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   11,
       15,   70,   21,   70,    0,   71,   73,    9,   70,   12,
       70,   70,   70,   23,   70,   26,   70,   70,   70,   70,
       70,   70,   70,   70,   34,   70,   70,   19,   70,   70,

       36,   70,   10,   70,   24,   70,   70,   70,   70,   70,
       70,   70,   70,   22,   70,   70,   70,   70,   70,   70,
       20,    7,   70,   70,    8,   25,   70,   16,   29,   30,
       17,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   26,   27,   25,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       28,   28,   28,   28,   30,   28,   28,   28,   28,   28,
       31,   32,   33,   34,   28,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   28,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   28,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    1,
        1,    1,    1,    1,    3,    3,    3,    4,    4,    4,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[240] =
    {   0,
        0,    0,  303,  302,  312,  315,  315,  315,  288,   58,
      315,  315,  278,  315,  315,  286,  315,  315,  315,  315,
       53,   76,   53,  315,  315,   43,  285,   50,    0,  315,
      315,  315,   29,  264,  258,  266,   32,  269,   58,  255,
       40,  251,  247,  261,   46,   51,  247,  250,   58,  315,
      315,  315,  315,  315,  281,  315,   81,  315,  293,  287,
      286,  315,  315,  290,   99,  104,  123,  315,   93,    0,
      315,  315,  315,  315,  315,    0,  254,  245,    0,  243,
      242,  252,  235,  232,  232,  239,    0,  234,   75,  234,
      237,   53,    0,  245,   73,  242,   91,    0,   73,  229,

      238,  231,  240,  231,  315,  315,  315,  265,  269,  315,
      127,  130,  133,  107,  106,    0,    0,  233,  218,  215,
      229,  221,  231,  213,  219,  220,  223,  212,  221,  212,
      209,  210,  213,  201,  201,  206,  211,  204,  211,  210,
        0,  213,  203,  201,  315,  150,  219,  315,    0,  191,
      202,    0,    0,    0,  203,  202,  193,  188,    0,  200,
      192,  183,  197,  182,  182,  189,  196,  185,  177,    0,
        0,  175,    0,  188,  153,  156,  315,    0,  178,    0,
      179,  185,  183,    0,  179,    0,  173,  167,  172,  170,
      172,  177,  172,  171,    0,  166,  173,    0,  176,  163,

        0,  158,    0,  139,    0,  131,  144,  136,  135,  132,
      141,  138,  125,    0,  117,  114,  120,   99,  102,  100,
        0,    0,   82,   34,    0,    0,   26,    0,    0,    0,
        0,  315,  187,  191,  195,  197,  201,  205,   64
    } ;

static const flex_int16_t yy_def[240] =
    {   0,
      232,    1,  233,  233,  232,  232,  232,  232,  232,  234,
      232,  232,  235,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  236,  232,
      232,  232,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  232,
      232,  232,  232,  232,  237,  232,  234,  232,  234,  232,
      235,  232,  232,  238,  232,  232,  232,  232,  232,  239,
      232,  232,  232,  232,  232,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,

      236,  236,  236,  236,  232,  232,  232,  232,  238,  232,
      232,  232,  232,  232,  239,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  232,  232,  232,  232,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  232,  232,  232,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,

      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,    0,  232,  232,  232,  232,  232,  232,  232
    } ;

static const flex_int16_t yy_nxt[378] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   29,   29,
       30,    6,   31,   32,   33,   34,   35,   36,   37,   38,
       29,   29,   39,   29,   40,   29,   41,   42,   29,   43,
       44,   45,   46,   47,   48,   49,   29,   29,   50,   51,
       52,   53,   58,   63,   71,   72,  115,   65,   64,   66,
       66,   66,   74,   75,   91,   77,   83,  231,   84,   67,
       78,   79,   68,   85,   96,   58,  230,   92,   97,   59,
       65,   67,   66,   66,   66,  130,  103,   87,   98,  104,

      131,   99,   67,   88,   89,   68,   68,  138,  100,  114,
      114,   69,   59,  133,   67,  111,  111,  111,   65,  126,
       66,   66,   66,  114,  114,  134,  139,  127,  229,   68,
       67,  136,   70,   68,  112,  148,  112,  137,  228,  113,
      113,  113,   67,  111,  111,  111,  113,  113,  113,  113,
      113,  113,  145,  146,  227,  147,  226,   68,  225,  148,
      224,  175,   68,  175,  223,  146,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  222,  221,  220,  219,  218,
      217,  145,  216,  215,  147,  214,   68,   54,   54,   54,
       54,   57,   57,   57,   57,   60,  213,   60,   60,   76,

       76,  105,  105,  105,  105,  109,  109,  109,  109,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  110,  107,  144,  143,  142,  141,  140,  135,  132,
      129,  128,  125,  124,  123,  122,  121,  120,  119,  118,
      117,  116,  110,  108,  107,  232,  106,  102,  101,   95,

       94,   93,   90,   86,   82,   81,   80,   73,   62,   61,
       56,  232,   55,   55,    5,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232
    } ;

static const flex_int16_t yy_chk[378] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   10,   21,   26,   26,  239,   23,   21,   23,
       23,   23,   28,   28,   41,   33,   37,  227,   37,   23,
       33,   33,   23,   37,   45,   57,  224,   41,   45,   10,
       22,   23,   22,   22,   22,   92,   49,   39,   46,   49,

       92,   46,   22,   39,   39,   22,   23,   99,   46,   69,
       69,   22,   57,   95,   22,   65,   65,   65,   66,   89,
       66,   66,   66,  114,  114,   95,   99,   89,  223,   22,
       66,   97,   22,   66,   67,  115,   67,   97,  220,   67,
       67,   67,   66,  111,  111,  111,  112,  112,  112,  113,
      113,  113,  111,  111,  219,  111,  218,   66,  217,  115,
      216,  146,  113,  146,  215,  111,  146,  146,  146,  175,
      175,  175,  176,  176,  176,  213,  212,  211,  210,  209,
      208,  176,  207,  206,  176,  204,  113,  233,  233,  233,
      233,  234,  234,  234,  234,  235,  202,  235,  235,  236,

      236,  237,  237,  237,  237,  238,  238,  238,  238,  200,
      199,  197,  196,  194,  193,  192,  191,  190,  189,  188,
      187,  185,  183,  182,  181,  179,  174,  172,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  158,  157,
      156,  155,  151,  150,  147,  144,  143,  142,  140,  139,
      138,  137,  136,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  119,
      118,  109,  108,  104,  103,  102,  101,  100,   96,   94,
       91,   90,   88,   86,   85,   84,   83,   82,   81,   80,
       78,   77,   64,   61,   60,   59,   55,   48,   47,   44,

       43,   42,   40,   38,   36,   35,   34,   27,   16,   13,
        9,    5,    4,    3,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[83] =
    {   0,
1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() (yyg->yy_more_flag = 1)
#define YY_MORE_ADJ yyg->yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
#line 2 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
#include "HeaderGlobals.h"
#include <FlexDependencies.h>
#include "Language_gen_y.hpp"

extern void unescape(char *s);
void update_loc(location_t *yylloc, int lineno, int leng, char *text);

#define YY_USER_ACTION update_loc(yylloc, yylineno, yyleng, yytext);
#line 855 "/home/alisson/Downloads/robcmp-svds_and_rp2040/build-pointer-test/Language_l.cpp"
#define YY_NO_INPUT 1

#line 858 "/home/alisson/Downloads/robcmp-svds_and_rp2040/build-pointer-test/Language_l.cpp"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 24 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"


#line 1144 "/home/alisson/Downloads/robcmp-svds_and_rp2040/build-pointer-test/Language_l.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yyg->yy_more_len = 0;
		if ( yyg->yy_more_flag )
			{
			yyg->yy_more_len = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			yyg->yy_more_flag = 0;
			}
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 233 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 315 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = yyg->yy_more_len; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 26 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ /* ignore spaces */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ yymore(); BEGIN COMMENT; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 28 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ yymore(); }
	YY_BREAK
case 4:
/* rule 4 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
yyg->yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 29 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ yymore(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 30 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 6:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 32 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ /* line comment */}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_REGISTER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_VOLATILE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_CONST; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_RETURN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_TRUE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_FALSE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_AT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_ASM; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_TYPE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_INTF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_IMPL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_USE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_INLINE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_NOINLINE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_WEAK; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_SECTION; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_NAKED; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_SIGNAL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_DEBUGONLY; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_NOOPT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 56 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_BIND; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 57 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_TO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 58 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_SINGLETON; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 59 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_TRANSIENT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 61 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_ENUM; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_IF; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_ELSE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_WHILE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_LOOP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_QUANDO; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_ESTA; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_AND; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_OR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_LSHIFT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_RSHIFT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return EQ_OP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return NE_OP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return LE_OP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return GE_OP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return LT_OP; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return GT_OP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 85 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '['; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 86 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return ']'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '('; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return ')'; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 91 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '{'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 92 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '}'; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return TOK_MUL_ASSIGN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '*'; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '/'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '+'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '-'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 99 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '%'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '='; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '|'; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '&'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '^'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '~'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '!'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 108 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return ':'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 109 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return '.'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 110 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return ','; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ return ';'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ yylval->ident = strndup(yytext, yyleng); 
						  return TOK_IDENTIFIER; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ char *aux = strndup(yytext, yyleng);
						  yylval->nfloat = strtof(aux, NULL);
						  free(aux);
						  return TOK_FLOAT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 121 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ char *aux = strndup(yytext, yyleng);
						  yylval->ndouble = strtod(aux, NULL);
						  free(aux);
						  return TOK_DOUBLE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 126 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ char *aux = strndup(yytext, yyleng);
						  yylval->nldouble = strtold(aux, NULL);
						  free(aux);
						  return TOK_LDOUBLE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 131 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ char *aux = strndup(yytext, yyleng);
						  yylval->nint = strtoll(aux, NULL, 16);
						  free(aux);
						  return TOK_INTEGER; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 136 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ char *aux = strndup(yytext, yyleng);
						  yylval->unint = strtoull(aux, NULL, 16);
						  free(aux);
						  return TOK_UINTEGER; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 141 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ char *aux = strndup(yytext+2, yyleng-2);
						  yylval->unint = strtoull(aux, NULL, 2);
						  free(aux);
						  return TOK_UINTEGER; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 146 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ char *aux = strndup(yytext, yyleng-1);
						  yylval->unint = (uint64_t)strtod(aux, NULL);
						  free(aux);
						  return TOK_UINTEGER; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 151 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ char *aux = strndup(yytext, yyleng);
						  yylval->nint = (int64_t)strtod(aux, NULL);
						  free(aux);
						  return TOK_INTEGER; }
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 156 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ yylval->str = strndup(yytext+1, yyleng-2);
						  unescape(yylval->str);
						  return TOK_STRING; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 160 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ char *aux = strndup(yytext+1, yyleng-2);
						  unescape(aux);
						  yylval->nint = aux[0];
						  free(aux);
						  return TOK_CHAR; }
	YY_BREAK
/* deixar por último. Caractere não reconhecido pelo alfabeto. */
case 81:
YY_RULE_SETUP
#line 167 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
{ yyerror(yylloc, NULL, string_format(COLOR_RED "lexical error:" COLOR_RED " unknown char '%c'.", yytext[0]).c_str()); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 169 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"
ECHO;
	YY_BREAK
#line 1672 "/home/alisson/Downloads/robcmp-svds_and_rp2040/build-pointer-test/Language_l.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 233 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 233 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 232);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 169 "/home/alisson/Downloads/robcmp-svds_and_rp2040/src/Language.l"


void update_loc(location_t *loc, int lineno, int leng, char *text) {
	loc->first_line = loc->last_line;
	loc->first_column = loc->last_column;
	if (loc->last_line == 0) { // first call
		loc->last_line = lineno;
		loc->last_column += leng;
	} else if (loc->last_line == lineno)
		loc->last_column += leng;
	else {
		loc->last_line = lineno;
		loc->last_column = text + leng - strrchr(text, '\n');
	}
}

#ifdef __MINGW64__
char *strndup(const char *s, size_t n) {
	size_t len = strnlen(s, n);
	char *newstr = (char*)malloc(len+1);
	if (!newstr)
		return NULL;
	newstr[len] = '\0';
	return (char*)memcpy(newstr, s, len);
}
#endif

