
#pragma once

#ifndef SCANNER_OR_VISITOR
#error Please include this file only on .y or visitor files
#endif

#include "HeaderGlobals.h"
#include "SourceLocation.h"
#include "Scanner.h"
#include "Node.h"
#include "ArrayElements.h"
#include "AttachInterrupt.h"
#include "BinaryOp.h"
#include "CmpOp.h"
#include "Double.h"
#include "Float.h"
#include "Float128.h"
#include "FunctionCall.h"
#include "FunctionDecl.h"
#include "FunctionImpl.h"
#include "Variable.h"
#include "If.h"
#include "Int1.h"
#include "Char.h"
#include "Int8.h"
#include "Int16.h"
#include "Int32.h"
#include "Int64.h"
#include "Load.h"
#include "LoadArray.h"
#include "LoadMatrix.h"
#include "Matrix.h"
#include "MatrixElements.h"
#include "ParamsCall.h"
#include "Program.h"
#include "Return.h"
#include "Scalar.h"
#include "semantic/Semantic.h"
#include "StringConst.h"
#include "UpdateArray.h"
#include "UpdateMatrix.h"
#include "Array.h"
#include "StringConst.h"
#include "While.h"
#include "Loop.h"
#include "Pointer.h"
#include "FlipOp.h"
#include "InlineAssembly.h"
#include "Interface.h"
#include "UserType.h"
#include "Enum.h"
#include "MemCopy.h"
#include "BackLLVM.h"
#include "NamedConst.h"
#include "BitCast.h"
#include "semantic/PropagateTypes.h"